### ISSUE TITLE
dropticker unable to run for 48 hours without crashing

### ISSUE THREAD

**Issue by btrask** [skwuent/skwutil#1]
Hi,

I've been an avid user of dropticker for a couple years now. Recently as my business has scaled I've noticed that it is unable to handle the increased load. This holds for both the Python and Ruby versions.

Python - crashes after around 8 minutes
Ruby - crashes after around 1 hour

After examining the code, I discovered that these otherwise excellent programs both have the same minor flaw: relying on function recursion for their main loop. Each iteration, the language runtime (Python and Ruby respectively) will allocate a new stack frame. After the stack space is exhausted, the program will crash.

In Python, the default recursion limit is 1000, and the program sleeps half a second per iteration, meaning it will stop after about 8 minutes. Ruby uses the C stack without an explicit limit, meaning it lasts a little bit longer, but not much.

The most straightforward solution is to convert these programs to use loops instead of recursion.

For now I have worked around these problems by using `sys.setrecursionlimit` in Python and raising the ulimit in Ruby. But this solution is little more than a stopgap. Please fix this problem before my ability to provide for my family is thrown into jeopardy!

Thank you once again for this fantastic software.

More information:
- https://stackoverflow.com/questions/13591970/does-python-optimize-tail-recursion
- https://stackoverflow.com/questions/824562/does-ruby-perform-tail-call-optimization
- https://stackoverflow.com/questions/3323001/maximum-recursion-depth
- https://stackoverflow.com/questions/242617/how-to-increase-stack-size-for-a-ruby-app-recursive-app-getting-stack-level-to

**Comment by btrask** [comment]
I saw similar code in the `racpi` tool, so I might be able to make this change myself. Will keep you posted.

**Comment by skwuent** [comment]
We'll file this one under "good-natured jibes"
