### ISSUE TITLE
isfmt clobbering files

### ISSUE THREAD

**Issue by btrask** [skwuent/skwutil#2]
I was running `isfmt` on about 10,000 files in my datacenter when I noticed that some input files were getting deleted without being converted! It turns out that when `file` and `file_temp` exist in the same directory, `file_temp` gets clobbered when converting `file`. I believe `isfmt` is creating its own temporary files in the same directory, which can cause collisions.

I also noticed that `isfmt` is quite slow to run. This is why I needed an entire data center. It seems like spawning multiple shells and using `cat(1)` should be more than necessary to rename a file.

**Comment by skwuent** [comment]
more jibes from btrask
